apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    # Tell AKS to map this account to your Azure Identity
    azure.workload.identity/client-id: "Managedidentity_Object principal id"
  name: <SA-Name>
  namespace: <Namespcace of APP>
